// apps/portal-react/react-produccion-guia/src/paginas/AdminDashboard.jsx
import React, { useContext } from "react";
import { AppContext } from "../context/AppContext";

export default function AdminDashboard() {
  const { courses, setVista } = useContext(AppContext);

  return (
    <div>
      <div className="page-header">
        <div className="page-header-row">
          <div>
            <h1 className="page-title">Dashboard administrativo</h1>
            <p className="page-subtitle">Resumen general del sistema de EduTech Academy.</p>
          </div>
          <div style={{ display: "flex", gap: "var(--space-2)" }}>
            <button className="btn btn-ghost btn-sm" onClick={() => alert("Exportando datos...")}>📥 Exportar reporte</button>
            <button className="btn btn-primary btn-sm" onClick={() => setVista("admin-cursos")}>+ Nuevo curso</button>
          </div>
        </div>
      </div>

      {/* Alert de atención */}
      <div className="alert alert-warning" style={{ marginBottom: "var(--space-6)" }} role="alert">
        <span className="alert-icon" aria-hidden="true">⚠️</span>
        <div className="alert-content">
          <div className="alert-title">Atención requerida</div>
          <div>Hay 3 solicitudes de inscripción pendientes de aprobación y 1 docente con verificación incompleta.</div>
        </div>
      </div>

      {/* Stats principales */}
      <div className="grid grid-4" style={{ marginBottom: "var(--space-6)" }}>
        <div className="stat-card">
          <div className="stat-icon blue">📚</div>
          <div className="stat-content">
            <div className="stat-label">Total cursos</div>
            <div className="stat-value">{courses.length}</div>
            <div className="stat-change up">↑ +3 este mes</div>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon green">👥</div>
          <div className="stat-content">
            <div className="stat-label">Total estudiantes</div>
            <div className="stat-value">1,240</div>
            <div className="stat-change up">↑ +87 este mes</div>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon purple">👨‍🏫</div>
          <div className="stat-content">
            <div className="stat-label">Total docentes</div>
            <div className="stat-value">12</div>
            <div className="stat-change up">↑ +1 este mes</div>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon yellow">📋</div>
          <div className="stat-content">
            <div className="stat-label">Inscripciones activas</div>
            <div className="stat-value">3,182</div>
            <div className="stat-change up">↑ +214 este mes</div>
          </div>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-6)" }}>
        
        {/* Cursos populares */}
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">Cursos con más inscritos</h2>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-4)" }}>
            {courses.slice(0, 3).map((c, idx) => (
              <div key={c.id} style={{ display: "flex", alignItems: "center", gap: "var(--space-3)" }}>
                <div style={{ width: "32px", height: "32px", borderRadius: "50%", background: "var(--primary-100)", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold", color: "var(--primary-600)" }}>
                  {idx + 1}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontWeight: 600, fontSize: "var(--text-sm)" }}>{c.title}</div>
                  <div className="progress-bar-bg" style={{ marginTop: "4px" }}>
                    <div className="progress-bar" style={{ width: `${80 - idx * 20}%` }}></div>
                  </div>
                </div>
                <div style={{ fontWeight: 700, color: "var(--primary-600)" }}>{c.studentsCount}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Accesos rápidos */}
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">Accesos rápidos</h2>
          </div>
          <div className="quick-access-grid">
            <a href="#" className="quick-card" onClick={(e) => { e.preventDefault(); setVista("admin-cursos"); }}>
              <div className="icon">📚</div>
              <div className="label">Cursos</div>
            </a>
            <a href="#" className="quick-card" onClick={(e) => { e.preventDefault(); setVista("admin-estudiantes"); }}>
              <div className="icon">👥</div>
              <div className="label">Estudiantes</div>
            </a>
            <a href="#" className="quick-card" onClick={(e) => { e.preventDefault(); setVista("admin-docentes"); }}>
              <div className="icon">👨‍🏫</div>
              <div className="label">Docentes</div>
            </a>
            <a href="#" className="quick-card" onClick={(e) => { e.preventDefault(); alert("Vista en desarrollo por colega."); }}>
              <div className="icon">🏆</div>
              <div className="label">Certificados</div>
            </a>
          </div>
        </div>

      </div>
    </div>
  );
}

// apps/admin-angular/admin-angular/src/app/components/admin-dashboard/admin-dashboard.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './admin-dashboard.component.html',
})
export class AdminDashboardComponent {}

<nav class="navbar" role="navigation" aria-label="Navegación administrativa">
  <div class="container">
    <a routerLink="/" class="navbar-brand">
      <div class="brand-icon" aria-hidden="true">🎓</div>
      <span>Edu<em>Tech</em> <span style="font-size:var(--text-xs);font-weight:700;background:var(--danger-600);color:var(--white);padding:2px 8px;border-radius:var(--border-radius-full);letter-spacing:.5px;">ADMIN</span></span>
    </a>
    <ul class="navbar-nav" role="list">
      <li><a routerLink="/admin-dashboard" class="active" aria-current="page">Dashboard</a></li>
      <li><a routerLink="/admin-cursos">Cursos</a></li>
      <li><a routerLink="/admin-estudiantes">Estudiantes</a></li>
      <li><a routerLink="/admin-docentes">Docentes</a></li>
    </ul>
    <div class="navbar-actions">
      <div class="navbar-user">
        <div class="avatar" style="background:linear-gradient(135deg,var(--danger-600),#9333ea);" aria-label="Foto del administrador">AD</div>
        <span style="font-size:var(--text-sm);font-weight:600;color:var(--gray-700);">Admin</span>
      </div>
      <button class="hamburger" id="hamburger" aria-label="Abrir menú" aria-expanded="false" aria-controls="mobile-nav">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</nav>
<div class="mobile-nav" id="mobile-nav">
  <a routerLink="/admin-dashboard">📊 Dashboard</a>
  <a routerLink="/admin-cursos">📚 Cursos</a>
  <a routerLink="/admin-estudiantes">👥 Estudiantes</a>
  <a routerLink="/admin-docentes">👨‍🏫 Docentes</a>
  <a href="login.html">🚪 Salir</a>
</div>

<div class="page-content">
  <div class="layout-with-sidebar">

    <aside class="sidebar" id="sidebar" aria-label="Menú de administración">
      <div class="sidebar-header">
        <div class="sidebar-user">
          <div class="avatar" style="background:linear-gradient(135deg,var(--danger-600),#9333ea);" aria-label="Administrador">AD</div>
          <div class="user-info">
            <div class="name">Administrador</div>
            <div class="role">Super Admin</div>
          </div>
        </div>
        <div class="sidebar-title">Panel de control</div>
      </div>
      <nav class="sidebar-nav" aria-label="Navegación administrativa">
        <a routerLink="/admin-dashboard" class="active" aria-current="page"><span class="nav-icon" aria-hidden="true">📊</span> Dashboard</a>

        <div class="sidebar-section-label">Gestión académica</div>
        <a routerLink="/admin-cursos"><span class="nav-icon" aria-hidden="true">📚</span> Cursos<span class="sidebar-badge">48</span></a>
        <a routerLink="/admin-estudiantes"><span class="nav-icon" aria-hidden="true">👥</span> Estudiantes<span class="sidebar-badge">1240</span></a>
        <a routerLink="/admin-docentes"><span class="nav-icon" aria-hidden="true">👨‍🏫</span> Docentes<span class="sidebar-badge">12</span></a>

        <div class="sidebar-section-label">Sistema</div>
        <a href="login.html"><span class="nav-icon" aria-hidden="true">🚪</span> Cerrar sesión</a>
      </nav>
    </aside>

    <main class="main-content">

      <div class="page-header">
        <div class="page-header-row">
          <div>
            <h1 class="page-title">Dashboard administrativo</h1>
            <p class="page-subtitle">Resumen general del sistema — Actualizado: lunes 06 de abril de 2026</p>
          </div>
          <div style="display:flex;gap:var(--space-3);">
            <button class="btn btn-ghost btn-sm">📥 Exportar</button>
            <a routerLink="/admin-cursos" class="btn btn-primary btn-sm">+ Nuevo curso</a>
          </div>
        </div>
      </div>

      <div class="alert alert-warning" style="margin-bottom:var(--space-6);" role="alert">
        <span class="alert-icon" aria-hidden="true">⚠️</span>
        <div class="alert-content">
          <div class="alert-title">Atención requerida</div>
          <div>Hay 3 solicitudes de inscripción pendientes de aprobación y 1 docente con verificación incompleta.</div>
        </div>
      </div>

      <div class="grid grid-4" style="margin-bottom:var(--space-8);" role="list" aria-label="Métricas generales">
        <div class="stat-card" role="listitem">
          <div class="stat-icon blue" aria-hidden="true">📚</div>
          <div class="stat-content">
            <div class="stat-label">Total cursos</div>
            <div class="stat-value">48</div>
            <div class="stat-change up">↑ +3 este mes</div>
          </div>
        </div>
        <div class="stat-card" role="listitem">
          <div class="stat-icon green" aria-hidden="true">👥</div>
          <div class="stat-content">
            <div class="stat-label">Total estudiantes</div>
            <div class="stat-value">1,240</div>
            <div class="stat-change up">↑ +87 este mes</div>
          </div>
        </div>
        <div class="stat-card" role="listitem">
          <div class="stat-icon purple" aria-hidden="true">👨‍🏫</div>
          <div class="stat-content">
            <div class="stat-label">Total docentes</div>
            <div class="stat-value">12</div>
            <div class="stat-change up">↑ +1 este mes</div>
          </div>
        </div>
        <div class="stat-card" role="listitem">
          <div class="stat-icon yellow" aria-hidden="true">📋</div>
          <div class="stat-content">
            <div class="stat-label">Inscripciones activas</div>
            <div class="stat-value">3,182</div>
            <div class="stat-change up">↑ +214 este mes</div>
          </div>
        </div>
      </div>

      <div class="grid grid-4" style="margin-bottom:var(--space-8);">
        <div class="stat-card">
          <div class="stat-icon green" aria-hidden="true">💰</div>
          <div class="stat-content">
            <div class="stat-label">Ingresos del mes</div>
            <div class="stat-value">S/ 42.5K</div>
            <div class="stat-change up">↑ +18% vs anterior</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon blue" aria-hidden="true">🏆</div>
          <div class="stat-content">
            <div class="stat-label">Certificados emitidos</div>
            <div class="stat-value">328</div>
            <div class="stat-change up">↑ +24 este mes</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon yellow" aria-hidden="true">⭐</div>
          <div class="stat-content">
            <div class="stat-label">Valoración promedio</div>
            <div class="stat-value">4.8</div>
            <div class="stat-change up">↑ +0.1 puntos</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon red" aria-hidden="true">📉</div>
          <div class="stat-content">
            <div class="stat-label">Tasa de abandono</div>
            <div class="stat-value">6.2%</div>
            <div class="stat-change down">↓ -1.3% mejoró</div>
          </div>
        </div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:var(--space-6);">

        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Cursos más inscritos</h2>
            <a routerLink="/admin-cursos" class="btn btn-ghost btn-sm">Ver todos →</a>
          </div>
          <div style="display:flex;flex-direction:column;gap:var(--space-4);">
            <div style="display:flex;align-items:center;gap:var(--space-3);">
              <div style="width:32px;height:32px;background:var(--primary-100);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:var(--text-sm);font-weight:900;color:var(--primary-600);flex-shrink:0;" aria-hidden="true">1</div>
              <div style="flex:1;">
                <div style="font-weight:600;font-size:var(--text-sm);">Desarrollo Frontend con React</div>
                <div class="progress-bar-bg" style="margin-top:var(--space-1);" aria-label="510 inscripciones, 100%"><div class="progress-bar" style="width:100%;"></div></div>
              </div>
              <div style="font-size:var(--text-sm);font-weight:700;color:var(--primary-600);flex-shrink:0;">510</div>
            </div>
            <div style="display:flex;align-items:center;gap:var(--space-3);">
              <div style="width:32px;height:32px;background:var(--accent-100);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:var(--text-sm);font-weight:900;color:var(--accent-600);flex-shrink:0;" aria-hidden="true">2</div>
              <div style="flex:1;">
                <div style="font-weight:600;font-size:var(--text-sm);">Programación Web II</div>
                <div class="progress-bar-bg" style="margin-top:var(--space-1);" aria-label="320 inscripciones, 63%"><div class="progress-bar" style="width:63%;"></div></div>
              </div>
              <div style="font-size:var(--text-sm);font-weight:700;color:var(--accent-600);flex-shrink:0;">320</div>
            </div>
            <div style="display:flex;align-items:center;gap:var(--space-3);">
              <div style="width:32px;height:32px;background:var(--success-100);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:var(--text-sm);font-weight:900;color:var(--success-600);flex-shrink:0;" aria-hidden="true">3</div>
              <div style="flex:1;">
                <div style="font-weight:600;font-size:var(--text-sm);">Backend con Node.js</div>
                <div class="progress-bar-bg" style="margin-top:var(--space-1);" aria-label="280 inscripciones, 55%"><div class="progress-bar success" style="width:55%;"></div></div>
              </div>
              <div style="font-size:var(--text-sm);font-weight:700;color:var(--success-600);flex-shrink:0;">280</div>
            </div>
            <div style="display:flex;align-items:center;gap:var(--space-3);">
              <div style="width:32px;height:32px;background:var(--warning-100);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:var(--text-sm);font-weight:900;color:var(--warning-600);flex-shrink:0;" aria-hidden="true">4</div>
              <div style="flex:1;">
                <div style="font-weight:600;font-size:var(--text-sm);">DevOps y CI/CD</div>
                <div class="progress-bar-bg" style="margin-top:var(--space-1);" aria-label="220 inscripciones, 43%"><div class="progress-bar warning" style="width:43%;"></div></div>
              </div>
              <div style="font-size:var(--text-sm);font-weight:700;color:var(--warning-600);flex-shrink:0;">220</div>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Accesos rápidos</h2>
          </div>
          <div class="quick-access-grid">
            <a routerLink="/admin-cursos" class="quick-card" aria-label="Gestionar cursos">
              <div class="icon" aria-hidden="true">📚</div>
              <div class="label">Cursos</div>
            </a>
            <a routerLink="/admin-estudiantes" class="quick-card" aria-label="Gestionar estudiantes">
              <div class="icon" aria-hidden="true">👥</div>
              <div class="label">Estudiantes</div>
            </a>
            <a routerLink="/admin-docentes" class="quick-card" aria-label="Gestionar docentes">
              <div class="icon" aria-hidden="true">👨‍🏫</div>
              <div class="label">Docentes</div>
            </a>
            <a href="#" class="quick-card" aria-label="Ver inscripciones pendientes">
              <div class="icon" aria-hidden="true">📋</div>
              <div class="label">Inscripciones</div>
            </a>
            <a href="#" class="quick-card" aria-label="Ver analíticas">
              <div class="icon" aria-hidden="true">📈</div>
              <div class="label">Analíticas</div>
            </a>
            <a href="#" class="quick-card" aria-label="Ver certificados">
              <div class="icon" aria-hidden="true">🏆</div>
              <div class="label">Certificados</div>
            </a>
            <a href="#" class="quick-card" aria-label="Facturación">
              <div class="icon" aria-hidden="true">💰</div>
              <div class="label">Facturación</div>
            </a>
            <a href="#" class="quick-card" aria-label="Configuración">
              <div class="icon" aria-hidden="true">⚙️</div>
              <div class="label">Configuración</div>
            </a>
          </div>
        </div>

      </div>

      <div class="card" style="margin-top:var(--space-6);">
        <div class="card-header">
          <h2 class="card-title">Últimas inscripciones</h2>
          <button class="btn btn-ghost btn-sm">Ver reporte completo →</button>
        </div>
        <div class="table-wrapper" style="border:none;box-shadow:none;border-radius:0;">
          <table class="table" aria-label="Últimas inscripciones registradas">
            <thead>
              <tr>
                <th scope="col">Estudiante</th>
                <th scope="col">Curso</th>
                <th scope="col">Fecha</th>
                <th scope="col">Monto</th>
                <th scope="col">Estado</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><div class="user-cell"><div class="avatar" aria-hidden="true">CG</div><div class="user-info"><div class="name">Carlos García</div><div class="sub">Ing. Sistemas</div></div></div></td>
                <td>Desarrollo Frontend con React</td>
                <td>06 abr 2024</td>
                <td><strong>S/ 180</strong></td>
                <td><span class="badge badge-success">Pagado</span></td>
              </tr>
              <tr>
                <td><div class="user-cell"><div class="avatar" style="background:linear-gradient(135deg,#7c3aed,#ec4899);" aria-hidden="true">AL</div><div class="user-info"><div class="name">Andrea López</div><div class="sub">Ing. Informática</div></div></div></td>
                <td>Bases de Datos NoSQL</td>
                <td>05 abr 2024</td>
                <td><strong>Gratuito</strong></td>
                <td><span class="badge badge-success">Activa</span></td>
              </tr>
              <tr>
                <td><div class="user-cell"><div class="avatar" style="background:linear-gradient(135deg,#059669,#0891b2);" aria-hidden="true">RM</div><div class="user-info"><div class="name">Roberto Méndez</div><div class="sub">Ing. Software</div></div></div></td>
                <td>Seguridad en Aplicaciones Web</td>
                <td>04 abr 2024</td>
                <td><strong>S/ 200</strong></td>
                <td><span class="badge badge-warning">Pendiente</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    </main>
  </div>
</div>
